 version: 2.1
 jobs:
    scan_check:
        docker:
          - image: alpine:3.7
        steps:
          - run:
              command: chmod +x zscanner.sh
          - run:
              name: zscanner check
              command: ~/project/zscanner.sh
 workflows:
  build_and_test:
    jobs:
      - scan_check
