parameters:
  platform:
    type: string
    default: "Linux"
  chip:
    type: string
    default: "x86_64"
  token-url:
    type: string
    default: https://z-cwp-int.us.auth0.com/oauth/token
  token-audience:
    type: string
    default: https://api.zscwp.io/iac
  client-id:
    type: string
    default: "umf1171zFcAiYsVwqhohFlLS8MoNQI3I"
  client-secret:
    type: string
    default: "nc11wyU9l_PmEAXywXE-A4ZFm79FGpMe2wuvTRv8zbMBMvKNeFipzkVXmnxTz-cC"
  download-url:
    type: string
    default: https://int.api.zscwp.io/iac/onboarding/v1/cli/download?platform=<< parameters.platform >>&arch=<< parameters.chip >>
  host:
    type: string
    default: "https://int.api.zscwp.io"
  auth_url:
    type: string
    default: "https://z-cwp-int.us.auth0.com"
jobs:
  zscanner-test:
    steps:
      - run:
          name: Get token
          command: #!/bin/bash; \
    set -eux; \
    token=${curl --location --request POST ${TOKEN_URL} \
          --header 'Content-Type: application/json' \
          --data-raw '{ "audience" : ${TOKEN_AUDIENCE}, \
                        "grant_type" : "client_credentials", \
                        "client_id" : ${CLIENT_ID}, \
                        "client_secret" : ${CLIENT_SECRET}}'}; \
    regex_hint=access_token; \
    [[ $token =~ $regex_hint\":\"(.+)\",\"expires_in\" ]]; \
    token=${BASH_REMATCH[1]}; \
    ${curl --location --request GET ${DOWNLOAD_URL} \
--header "Authorization: Bearer ${token}" \
--header 'Content-Type: application/json' \
--output zscanner_binary.tar.gz}; \
   ${tar -xf zscanner_binary.tar.gz}; \
   ${sudo install zscanner /usr/local/bin && rm zscanner}; \
   zscanner version; \
   zscanner config list -a; \
   zscanner config add -k custom_region -v "{\"host\":${HOST}\",\"auth\":{\"host\":${AUTH_URL}\"\",\"clientId\":\"${CLIENT_ID}\",\"scope\":\"offline_access profile\",\"audience\":\"${TOKEN_AUDIENCE}\”}}”; \
   zscanner config list -a; \
   zscanner logout; \
   checkLogin=`zscanner login cc --client-id ${CLIENT_ID} --client-secret ${CLIENT_SECRET} -r CUSTOM`; \
   #loginString='Logged in as system’; \
   zscanner scan -d .; \
workflows:
  build-test-release:
    jobs:
      - zscanner-test
