 version: 2.1
 jobs:
    scan_check:
        docker:
          - image: circleci/node:lts
        steps:
          - checkout
          - run:
              command: chmod +x ./zscanner.sh
          - run:
              name: zscanner check
              command: ./zscanner.sh
 workflows:
  build_and_test:
    jobs:
      - scan_check
