 version: 2.1
 jobs:
    scan_check:
        docker:
          - image: alpine:3.7
        steps:
          - run:
              name: zscanner check
              shell: bash.exe
              command: ./zscanner.sh
 workflows:
  build_and_test:
    jobs:
      - scan_check
